basePath: /api/v1
definitions:
  controllers._RequestCreateTask:
    properties:
      content:
        description: 备忘录内容
        example: 生命不惜，卷卷不止~~
        type: string
      title:
        description: 备忘录标题
        example: 卷卷卷
        type: string
    required:
    - content
    - title
    type: object
  controllers._ResponseCreateTask:
    properties:
      code:
        description: 状态码
        example: 1000
        type: integer
      msg:
        description: 信息
        example: Success!!
        type: string
    type: object
  controllers._ResponseLogin:
    properties:
      code:
        description: 状态码
        example: 1000
        type: integer
      data:
        description: 数据
      msg:
        description: 信息
        example: Success!!
        type: string
    type: object
  controllers._ResponseRegister:
    properties:
      code:
        description: 状态码
        example: 1000
        type: integer
      msg:
        description: 信息
        example: Success!!
        type: string
    type: object
  controllers._ResponseShowATask:
    properties:
      code:
        description: 状态码
        example: 1000
        type: integer
      data:
        $ref: '#/definitions/models.Task'
        description: 具体task信息
      msg:
        description: 信息
        example: Success!!
        type: string
    type: object
  models.LoginParams:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  models.RegisterParams:
    properties:
      password:
        description: 密码
        type: string
      re_password:
        description: 再次确认密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - re_password
    - username
    type: object
  models.Task:
    properties:
      content:
        description: 备忘录内容
        type: string
      create_time:
        description: 备忘录创建时间
        type: string
      end_time:
        description: 备忘录结束时间
        type: string
      start_time:
        description: 备忘录开始时间
        type: string
      status:
        description: 完成状态，默认0（未完成），1（完成）
        type: integer
      task_id:
        description: 备忘录id
        type: integer
      title:
        description: 备忘录标题
        type: string
      update_time:
        description: 备忘录最新修改时间
        type: string
      user_id:
        description: 创建者id
        example: "0"
        type: string
    required:
    - content
    - title
    type: object
host: localhost:8080
info:
  contact: {}
  description: Personal projects
  title: ziweiMemo
  version: v1.0.0
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 需要上传的json
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.LoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers._ResponseLogin'
      summary: 用户登录的接口
      tags:
      - 用户接口
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 需要上传的json
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/models.RegisterParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers._ResponseRegister'
      summary: 用户注册的接口
      tags:
      - 用户接口
  /task:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: 需要上传的json
        in: body
        name: create_task
        required: true
        schema:
          $ref: '#/definitions/controllers._RequestCreateTask'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers._ResponseCreateTask'
      summary: 创建task的接口
      tags:
      - task接口
  /task/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers._ResponseShowATask'
      summary: 展示一条task详情的接口
      tags:
      - task接口
swagger: "2.0"
